### PR TITLE
Add CustomEvent polyfill

### PR DESCRIPTION
**Pull request by jharrilim**
## Description

Fix for: https://github.com/rehooks/local-storage/issues/77

### Example with polyfill

image

### Example with the browser's CustomEvent

image

### CODE REVIEW

**Comment by garritfra** [comment]
@jharrilim @iamsolankiamit Sorry for bothering, but what's the status on this? I just ran into the issue described in #77, and it would be awesome if this fixes the problem!

**Comment by 3AHAT0P** [comment]
Hi guys!
I'm very interested in this PR.
Any updates yet?
@iamsolankiamit could you check it PR?
@jharrilim could you assign another one reviewer?

**Comment by Sharpek** [comment]
Waiting for this.

**Comment by jharrilim** [comment]
Hi @hanford, would you be able to add the `NPM_TOKEN` to this repo's [Environment secrets](https://github.com/rehooks/local-storage/settings/secrets/actions/new) so we may publish this package via CI?

Or if possible, can you add me to the Github and NPM org so I may set it up?

**Pull request merged**
