### PR TITLE
Update use-localstorage.ts

### PR DESCRIPTION
**Pull request by gmdayley**
Fixes issue in Safari not handling custom LocalStorageChanged event.

### CODE REVIEW

**Comment by yoshioteruia** [comment]
Is someone looking at it? I tested on my app and it worked

**Comment by jharrilim** [comment]
Sorry I forgot to reply to this earlier! I had tried it out and was unable to compile. Instead I had to create this function:

```ts
/**
 * Checks if the event that is passed in is the same type as LocalStorageChanged.
 *
 * @export
 * @template TValue
 * @param {*} evt the object you wish to assert as a LocalStorageChanged event.
 * @returns {evt is LocalStorageChanged<TValue>} if true, evt is asserted to be LocalStorageChanged.
 */
export function isTypeOfLocalStorageChanged<TValue>(evt: any): evt is LocalStorageChanged<TValue> {
    return (!!evt) && (evt instanceof LocalStorageChanged || (evt.detail && evt.type === LocalStorageChanged.eventName));
}
```
I am unsure though why that fix was able to work for you but not for me. Please check if my solution also works for you.

**Comment by yoshioteruia** [comment]
@jharrilim I tried your solution and it worked! I tested it on safari and chrome! Thanks!

**Comment by iamsolankiamit** [comment]
published in [v1.7.0](https://github.com/rehooks/local-storage/releases/tag/v1.7.0)

**Pull request merged**
